packageExtensions:
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@nestjs/common@*':
    dependencies:
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      '@nestjs/platform-socket.io': '*'
      reflect-metadata: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@nestjs/websockets': '*'
      '@nestjs/platform-socket.io': '*'
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      reflect-metadata: '*'
      kafkajs: '*'
  typeorm@*:
    dependencies:
      pg: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220325.hash-c66fcd9.cjs
