packageExtensions:
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
      protobufjs: '*'
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@atls/nestjs-gateway@*':
    dependencies:
      ws: '*'
  '@graphql-mesh/store@*':
    dependencies:
      '@graphql-mesh/types': '*'
  '@graphql-mesh/types@*':
    dependencies:
      '@graphql-mesh/store': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    dependencies:
      '@vue/compiler-sfc': '*'
      svelte2tsx: '*'
  '@graphql-typed-document-node/core@*':
    dependencies:
      graphql: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@nestjs/common@*':
    dependencies:
      cache-manager: '*'
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      '@nestjs/platform-socket.io': '*'
      reflect-metadata: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@nestjs/websockets': '*'
      '@nestjs/platform-socket.io': '*'
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      reflect-metadata: '*'
      kafkajs: '*'
  typeorm@*:
    dependencies:
      pg: '*'
  svelte2tsx@*:
    dependencies:
      svelte: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  graphql-tag@*:
    dependencies:
      graphql: '*'
  debug@*:
    dependencies:
      supports-color: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220325.hash-c66fcd9.cjs
