name: Checks

on: [pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: TypeCheck
        run: yarn typecheck

      - name: TestUnit
        run: yarn test unit

      - name: TestIntegration
        run: yarn test integration

      - name: Release
        run: yarn workspaces foreach --include '@*/*-entrypoint' run build
